package postgres

import (
	"context"
	"fmt"
	"io/fs"
	"reflect"
	"sort"
	"strings"
	"testing"
	"testing/fstest"

	"fractallegend/game-server/internal/contribution"
	"fractallegend/game-server/internal/emission"
	"fractallegend/game-server/internal/miningblock"
	"fractallegend/game-server/internal/systemspend"
	"github.com/jackc/pgx/v5"
)

func g21MigrationThrough(t *testing.T, last string) fstest.MapFS {
	t.Helper()
	source := fstest.MapFS{}
	entries, err := fs.ReadDir(migrations, "migrations")
	if err != nil {
		t.Fatal(err)
	}
	for _, entry := range entries {
		if entry.Name()[:4] > last {
			continue
		}
		name := "migrations/" + entry.Name()
		data, err := fs.ReadFile(migrations, name)
		if err != nil {
			t.Fatal(err)
		}
		source[name] = &fstest.MapFile{Data: data}
	}
	return source
}

func g21MigrationRows(t *testing.T, s *Store) map[string]string {
	t.Helper()
	ctx := context.Background()
	rows, err := s.pool.Query(ctx, `SELECT tablename FROM pg_tables WHERE schemaname='public' AND tablename<>'schema_migrations' ORDER BY tablename`)
	if err != nil {
		t.Fatal(err)
	}
	var names []string
	for rows.Next() {
		var name string
		if err = rows.Scan(&name); err != nil {
			t.Fatal(err)
		}
		names = append(names, name)
	}
	err = rows.Err()
	rows.Close()
	if err != nil {
		t.Fatal(err)
	}
	result := map[string]string{}
	for _, name := range names {
		var raw string
		if err = s.pool.QueryRow(ctx, `SELECT COALESCE(jsonb_agg(r ORDER BY r::text),'[]'::jsonb)::text FROM (SELECT to_jsonb(t)-'item_revision'-'settlement_consumption_id' r FROM `+pgx.Identifier{name}.Sanitize()+` t) q`).Scan(&raw); err != nil {
			t.Fatal(err)
		}
		result[name] = raw
	}
	return result
}

// Restore only columns present in the real 0014 schema. Source histories were
// generated by authoritative services (R10, real seals/G19 receipts/P0 lots),
// not hand-edited reservation amounts. Replication mode is fixture loading only.
func g21RestorePriorSchemaHistory(t *testing.T, s *Store, history map[string]string) {
	t.Helper()
	ctx := context.Background()
	if _, err := s.pool.Exec(ctx, `DROP SCHEMA public CASCADE; CREATE SCHEMA public`); err != nil {
		t.Fatal(err)
	}
	if err := s.MigrateFS(ctx, g21MigrationThrough(t, "0014")); err != nil {
		t.Fatal(err)
	}
	tables := g21MigrationRows(t, s)
	var names []string
	for name := range tables {
		names = append(names, name)
	}
	sort.Strings(names)
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		t.Fatal(err)
	}
	defer tx.Rollback(ctx)
	if _, err = tx.Exec(ctx, `SET LOCAL session_replication_role=replica`); err != nil {
		t.Fatal(err)
	}
	var quoted []string
	for _, name := range names {
		quoted = append(quoted, pgx.Identifier{name}.Sanitize())
	}
	if _, err = tx.Exec(ctx, "TRUNCATE "+strings.Join(quoted, ",")+" CASCADE"); err != nil {
		t.Fatal(err)
	}
	for _, name := range names {
		rows, err := tx.Query(ctx, `SELECT column_name FROM information_schema.columns WHERE table_schema='public' AND table_name=$1 AND is_generated='NEVER' ORDER BY ordinal_position`, name)
		if err != nil {
			t.Fatal(err)
		}
		var cols []string
		for rows.Next() {
			var col string
			if err = rows.Scan(&col); err != nil {
				t.Fatal(err)
			}
			cols = append(cols, pgx.Identifier{col}.Sanitize())
		}
		err = rows.Err()
		rows.Close()
		if err != nil {
			t.Fatal(err)
		}
		raw, ok := history[name]
		if !ok {
			t.Fatalf("missing old-table fixture %s", name)
		}
		if _, err = tx.Exec(ctx, "INSERT INTO "+pgx.Identifier{name}.Sanitize()+"("+strings.Join(cols, ",")+") SELECT "+strings.Join(cols, ",")+" FROM jsonb_populate_recordset(NULL::"+pgx.Identifier{name}.Sanitize()+",$1::jsonb)", raw); err != nil {
			t.Fatalf("restore %s: %v", name, err)
		}
	}
	if err = tx.Commit(ctx); err != nil {
		t.Fatal(err)
	}
	var mode string
	if err = s.pool.QueryRow(ctx, `SHOW session_replication_role`).Scan(&mode); err != nil || mode != "origin" {
		t.Fatalf("fixture leaked bypass %s %v", mode, err)
	}
}

func TestG21ClosureT108CleanAndPriorHistoryMigration(t *testing.T) {
	t.Run("clean", func(t *testing.T) {
		s := integrationStore(t)
		ctx := context.Background()
		if err := s.Migrate(ctx); err != nil {
			t.Fatal(err)
		}
		before := g21ClosureSnapshot(t, s)
		if err := s.Migrate(ctx); err != nil {
			t.Fatal(err)
		}
		if before != g21ClosureSnapshot(t, s) {
			t.Fatal("repeat migration changed rows")
		}
		var versions, receipts int
		if err := s.pool.QueryRow(ctx, `SELECT (SELECT count(*) FROM schema_migrations),(SELECT count(*) FROM mining_reward_settlement_receipts)`).Scan(&versions, &receipts); err != nil || versions != 15 || receipts != 0 {
			t.Fatalf("clean versions/receipts=%d/%d %v", versions, receipts, err)
		}
	})
	t.Run("0014-history-to-0015", func(t *testing.T) {
		s, p, i := g21LegacyRewardFixture(t)
		ctx := context.Background()
		g19, err := s.MigrateBlackIronInventory(ctx, p.PlayerID)
		if err != nil {
			t.Fatal(err)
		}
		g21InventoryCommand(t, s, i, "unused-command")
		if _, err = s.createMiningRewardIssuancePrerequisiteTEST(ctx, "prior-p0-lot", i.BlockInstanceID, p.PlayerID, 3); err != nil {
			t.Fatal(err)
		}
		var source string
		if err = s.pool.QueryRow(ctx, `SELECT reservation_source_id FROM mining_reservation_instance_bindings WHERE block_instance_id=$1`, i.BlockInstanceID).Scan(&source); err != nil {
			t.Fatal(err)
		}
		if err = s.transferReservedToDistributedPrerequisiteTEST(ctx, source); err != nil {
			t.Fatal(err)
		}
		original := g21MigrationRows(t, s)
		g21RestorePriorSchemaHistory(t, s, original)
		before := g21MigrationRows(t, s)
		if r, e := s.ReconcileMiningRewardIssuancePrerequisite(ctx); e != nil || !r.Balanced {
			t.Fatalf("pre0015 P0 audit=%+v %v", r, e)
		}
		if err = s.Migrate(ctx); err != nil {
			t.Fatal(err)
		}
		after := g21MigrationRows(t, s)
		for table, rows := range before {
			if rows != after[table] {
				t.Errorf("0015 changed prior rows: %s", table)
			}
		}
		var activityCount, receipts, lots int
		if err = s.pool.QueryRow(ctx, `SELECT (SELECT sum(activity_count) FROM mining_power_activity_admission_counts),(SELECT count(*) FROM mining_reward_settlement_receipts),(SELECT count(*) FROM mining_reward_issuance_lots)`).Scan(&activityCount, &receipts, &lots); err != nil || activityCount != 1 || receipts != 0 || lots != 1 {
			t.Fatalf("metadata/economic cardinality=%d/%d/%d %v", activityCount, receipts, lots, err)
		}
		var originModes int
		if err = s.pool.QueryRow(ctx, `SELECT count(*) FROM mining_reward_origin_modes WHERE block_instance_id=$1 AND origin_mode='P0_SYNTHETIC_ONLY'`, i.BlockInstanceID).Scan(&originModes); err != nil || originModes != 1 {
			t.Fatalf("0014 P0 origin metadata=%d %v", originModes, err)
		}
		replay, err := s.MigrateBlackIronInventory(ctx, p.PlayerID)
		if err != nil || !reflect.DeepEqual(g19, replay) {
			t.Fatalf("prior G19 receipt changed=%+v %v", replay, err)
		}
		if r, e := s.ReconcileBlackIronEmission(ctx); e != nil || !r.Balanced {
			t.Fatalf("history emission audit=%+v %v", r, e)
		}
		if r, e := s.ReconcileMiningRewardIssuancePrerequisite(ctx); e != nil || !r.Balanced {
			t.Fatalf("history issuance audit=%+v %v", r, e)
		}
	})
}

func TestG21ClosureT109MigrationDDLFailureRollsBackAndRetries(t *testing.T) {
	s := integrationStore(t)
	ctx := context.Background()
	if err := s.MigrateFS(ctx, g21MigrationThrough(t, "0014")); err != nil {
		t.Fatal(err)
	}
	before := g21ClosureSnapshot(t, s)
	broken := g21MigrationThrough(t, "0015")
	name := "migrations/0015_test_mining_reward_settlement.sql"
	broken[name] = &fstest.MapFile{Data: append(append([]byte{}, broken[name].Data...), []byte("\nSELECT 1/0;\n")...)}
	if err := s.MigrateFS(ctx, broken); err == nil {
		t.Fatal("broken migration succeeded")
	}
	if before != g21ClosureSnapshot(t, s) {
		t.Fatal("failed DDL left data/schema/registry changes")
	}
	var rewardTable, itemColumn bool
	if err := s.pool.QueryRow(ctx, `SELECT to_regclass('public.mining_reward_commands') IS NOT NULL,EXISTS(SELECT 1 FROM information_schema.columns WHERE table_name='character_inventory_items' AND column_name='item_revision')`).Scan(&rewardTable, &itemColumn); err != nil || rewardTable || itemColumn {
		t.Fatalf("partial DDL=%t/%t %v", rewardTable, itemColumn, err)
	}
	if err := s.Migrate(ctx); err != nil {
		t.Fatal(err)
	}
	if err := s.Migrate(ctx); err != nil {
		t.Fatal(err)
	}
	var count int
	if err := s.pool.QueryRow(ctx, `SELECT count(*) FROM schema_migrations WHERE version=15`).Scan(&count); err != nil || count != 1 {
		t.Fatalf("retry registry=%d %v", count, err)
	}
}

func TestG21ClosureT110ZeroDistributedWriterRejectedAfterSettlement(t *testing.T) {
	s, cmd, receipt := g21ConstraintFixture(t)
	ctx := context.Background()
	before := g21ClosureSnapshot(t, s)
	// The prior zero-D formula cannot be resumed after G21 is stopped. This
	// models its actual aggregate UPDATE under the current conservation guard.
	if _, err := s.pool.Exec(ctx, `UPDATE black_iron_emission_pools SET remaining_capacity=total_emission_capacity-total_reserved+recovery_debt,revision=revision+1 WHERE pool_id='GLOBAL'`); err == nil {
		t.Fatal("zero-D writer accepted after reward distribution")
	}
	if before != g21ClosureSnapshot(t, s) {
		t.Fatal("old writer changed history")
	}
	replay, err := s.SettleMiningRewardTEST(ctx, cmd)
	if err != nil || !reflect.DeepEqual(replay, receipt) {
		t.Fatalf("compatible FINAL read/replay=%+v %v", replay, err)
	}
}

func TestG21ClosureT121G17G18LifecycleWithConsumedReservation(t *testing.T) {
	s, cmd, receipt := g21ConstraintFixture(t)
	ctx := context.Background()
	svc := miningblock.NewService(s, miningblock.DevelopmentRuleVersion, false)
	spend, err := systemspend.NewService(s, g15Registry(t)).Post(ctx, g15Intent("closure-regression-spend", 20))
	if err != nil {
		t.Fatal(err)
	}
	issuance, err := emission.NewService(s, emission.DevelopmentRuleVersion).Apply(ctx, spend.ID)
	if err != nil {
		t.Fatal(err)
	}
	cancelled, err := svc.Create(ctx, "closure-regression-cancel")
	if err != nil {
		t.Fatal(err)
	}
	cancellation, err := svc.Cancel(ctx, cancelled.BlockID)
	if err != nil {
		t.Fatal(err)
	}
	open, err := svc.Create(ctx, "closure-regression-finalize")
	if err != nil {
		t.Fatal(err)
	}
	finalized, err := s.FinalizeMiningBlock(ctx, open.BlockID)
	if err != nil {
		t.Fatal(err)
	}
	refund, err := contribution.NewService(s).RefundSystemSpend(ctx, g15Refund(spend, "closure-regression-refund", 15))
	if err != nil {
		t.Fatal(err)
	}
	if r, e := s.ReconcileBlackIronEmission(ctx); e != nil || !r.Balanced {
		t.Fatalf("extended conservation=%+v %v", r, e)
	}
	snap, err := s.SnapshotBlackIronEmission(ctx)
	if err != nil || snap.Pool.TotalEmissionCapacity != 25 || snap.Pool.TotalReserved != 10 || snap.Pool.TotalDistributed != 10 || snap.Pool.RemainingCapacity != 5 || snap.Pool.RecoveryDebt != 0 {
		t.Fatalf("C/S/D/M/H=%+v %v", snap.Pool, err)
	}
	before := g21ClosureSnapshot(t, s)
	if r, e := emission.NewService(s, emission.DevelopmentRuleVersion).Apply(ctx, spend.ID); e != nil || !reflect.DeepEqual(r, issuance) {
		t.Fatalf("G17 replay=%+v %v", r, e)
	}
	if r, e := svc.Cancel(ctx, cancelled.BlockID); e != nil || !reflect.DeepEqual(r, cancellation) {
		t.Fatalf("G18 cancel replay=%+v %v", r, e)
	}
	if r, e := s.FinalizeMiningBlock(ctx, open.BlockID); e != nil || !reflect.DeepEqual(r, finalized) {
		t.Fatalf("G18 finalize replay=%+v %v", r, e)
	}
	if r, e := contribution.NewService(s).RefundSystemSpend(ctx, g15Refund(spend, "closure-regression-refund", 15)); e != nil || !reflect.DeepEqual(r, refund) {
		t.Fatalf("refund replay=%+v %v", r, e)
	}
	if r, e := s.SettleMiningRewardTEST(ctx, cmd); e != nil || !reflect.DeepEqual(r, receipt) {
		t.Fatalf("G21 replay=%+v %v", r, e)
	}
	if before != g21ClosureSnapshot(t, s) {
		t.Fatal("cross-version replay changed persisted history")
	}
	t.Log(fmt.Sprintf("C25=S10+D10+M5-H0, FINAL=%s", receipt.SettlementID))
}
